### ISSUE TITLE
Cursor not found after processing ~3500 records

### ISSUE THREAD

**Issue by cdparra** [ParticipaPY/politic-bots#49]
Logs: 
```
INFO:root:Identifying 3322/67792 tweets (relevant)
INFO:root:Marking 0 RTS...

==> politic-bots-error.log <==
Traceback (most recent call last):
  File "run.py", line 92, in <module>
    run_task()
  File "/home/participa/politic-bots-generales/politic-bots/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/participa/politic-bots-generales/politic-bots/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/participa/politic-bots-generales/politic-bots/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/participa/politic-bots-generales/politic-bots/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "run.py", line 77, in run_task
    analyze_tweet_relevance()
  File "run.py", line 50, in analyze_tweet_relevance
    te.identify_relevant_tweets()
  File "/home/participa/politic-bots-generales/politic-bots/src/utils/data_wrangler.py", line 103, in identify_relevant_tweets
    for doc in search_res: 
  File "/home/participa/politic-bots-generales/politic-bots/env/lib/python3.5/site-packages/pymongo/cursor.py", line 1176, in next
    if len(self.__data) or self._refresh():
  File "/home/participa/politic-bots-generales/politic-bots/env/lib/python3.5/site-packages/pymongo/cursor.py", line 1110, in _refresh
    self.__send_message(g)
  File "/home/participa/politic-bots-generales/politic-bots/env/lib/python3.5/site-packages/pymongo/cursor.py", line 974, in __send_message
    helpers._check_command_response(first)
  File "/home/participa/politic-bots-generales/politic-bots/env/lib/python3.5/site-packages/pymongo/helpers.py", line 143, in _check_command_response
    raise CursorNotFound(errmsg, code, response)
pymongo.errors.CursorNotFound: cursor id 28124978271 not found
```

Possible solutions
- [ ] Reducing the batch size to keep the cursor alive.
- [X] Remove the timeout from the cursor.
- [X] Retry when the cursor expires.

Not recommended, but posible: 
- [ ] Query the results in batches manually.
- [ ] Get all the documents before the cursor expires.

Sources: 
https://stackoverflow.com/questions/38735225/typeerror-init-got-an-unexpected-keyword-argument-timeout-pymongo
https://stackoverflow.com/questions/44248108/mongodb-error-getmore-command-failed-cursor-not-found/44250410#44250410
https://stackoverflow.com/questions/50760889/pymongo-errors-cursornotfound-cursor-id-not-found-at-server

**Comment by cdparra** [comment]
Fixed by commit 6af476a79ae8185d74783f920875518239dd1602
